version: '3.5'

services:
  server: 
    container_name: apollo-test.app
    image: node:12.2
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/ # ホストのnode_modules使わない
    command: bash -c "yarn && yarn dev"
    ports:
      - 8080:8080
    networks:
      network:
        aliases:
          - app

networks:
  network:
    name: apollo-test
